export const API_ENDPOINTS = {
  LOGIN: '/Account/login',
  REGISTER: '/Account/register',
  CATEGORY: '/Category',
  PRODUCTS: '/products',
  TABLES: '/tables',
  OCCUPIED_TABLES: '/tables/occupiedtables',
  MY_TABLES: '/tables/my-tables',
  ORDERS: '/orders',
  MY_ORDERS: '/orders/my-orders',
  BILL: '/bill',
  ALL_BILLS: '/bill/all',
  CREATE_BILL: '/bill/create',
  USERS: '/User/all',
  ASSIGN_ROLE: (userId: string) => `/user/${userId}/assign-role`,
  REMOVE_ROLE: (userId: string) => `/user/${userId}/remove-role`,
}
